modLoader = "kotlinforforge"
loaderVersion = "[3,)"
license = "MIT"

issueTrackerURL = "https://github.com//issues"

[[mods]]
modId = "net"
version = "${file.jarVersion}"
displayName = "Marshie's Metahexes"
displayURL = "https://github.com/"
logoFile = "logo.png"
credits = "Petrak@ for the Project Layout, grywo for turning it into a template"
authors = "MarshmellowFluf"
description = "An add-on for Hex Casting."

[[dependencies.net]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.net]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
